//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Application.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Application.xsd", IsNullable=false)]
public partial class Application {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddressHistory", typeof(ApplicationAddressHistory))]
    [System.Xml.Serialization.XmlElementAttribute("Applicant", typeof(ApplicationApplicant))]
    [System.Xml.Serialization.XmlElementAttribute("EmploymentHistory", typeof(ApplicationEmploymentHistory))]
    [System.Xml.Serialization.XmlElementAttribute("Occupants", typeof(ApplicationOccupants))]
    [System.Xml.Serialization.XmlElementAttribute("Pets", typeof(ApplicationPets))]
    [System.Xml.Serialization.XmlElementAttribute("ResidentApplication", typeof(ApplicationResidentApplication))]
    [System.Xml.Serialization.XmlElementAttribute("Vehicles", typeof(ApplicationVehicles))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Application.xsd")]
public partial class ApplicationAddressHistory {
    
    private int addHistory_IDField;
    
    private string landlordCompanyNameField;
    
    private string addressField;
    
    private string phoneField;
    
    private string startEndDateField;
    
    private string cityStateZipField;
    
    private int applicant_IDField;
    
    private bool applicant_IDFieldSpecified;
    
    /// <remarks/>
    public int AddHistory_ID {
        get {
            return this.addHistory_IDField;
        }
        set {
            this.addHistory_IDField = value;
        }
    }
    
    /// <remarks/>
    public string LandlordCompanyName {
        get {
            return this.landlordCompanyNameField;
        }
        set {
            this.landlordCompanyNameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string StartEndDate {
        get {
            return this.startEndDateField;
        }
        set {
            this.startEndDateField = value;
        }
    }
    
    /// <remarks/>
    public string CityStateZip {
        get {
            return this.cityStateZipField;
        }
        set {
            this.cityStateZipField = value;
        }
    }
    
    /// <remarks/>
    public int Applicant_ID {
        get {
            return this.applicant_IDField;
        }
        set {
            this.applicant_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Applicant_IDSpecified {
        get {
            return this.applicant_IDFieldSpecified;
        }
        set {
            this.applicant_IDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Application.xsd")]
public partial class ApplicationApplicant {
    
    private int applicant_IDField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string phoneField;
    
    private string socialField;
    
    private System.DateTime dOBField;
    
    private bool dOBFieldSpecified;
    
    private string driversLicenseNumField;
    
    private string emailField;
    
    private int application_IDField;
    
    private bool isPrimaryField;
    
    /// <remarks/>
    public int Applicant_ID {
        get {
            return this.applicant_IDField;
        }
        set {
            this.applicant_IDField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string Social {
        get {
            return this.socialField;
        }
        set {
            this.socialField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DOBSpecified {
        get {
            return this.dOBFieldSpecified;
        }
        set {
            this.dOBFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string DriversLicenseNum {
        get {
            return this.driversLicenseNumField;
        }
        set {
            this.driversLicenseNumField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public int Application_ID {
        get {
            return this.application_IDField;
        }
        set {
            this.application_IDField = value;
        }
    }
    
    /// <remarks/>
    public bool IsPrimary {
        get {
            return this.isPrimaryField;
        }
        set {
            this.isPrimaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Application.xsd")]
public partial class ApplicationEmploymentHistory {
    
    private int empHistory_IDField;
    
    private string companyField;
    
    private string addressField;
    
    private string phoneField;
    
    private string startEndDateField;
    
    private int grossMonthlyIncomeField;
    
    private bool grossMonthlyIncomeFieldSpecified;
    
    private int applicant_IDField;
    
    /// <remarks/>
    public int EmpHistory_ID {
        get {
            return this.empHistory_IDField;
        }
        set {
            this.empHistory_IDField = value;
        }
    }
    
    /// <remarks/>
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string StartEndDate {
        get {
            return this.startEndDateField;
        }
        set {
            this.startEndDateField = value;
        }
    }
    
    /// <remarks/>
    public int GrossMonthlyIncome {
        get {
            return this.grossMonthlyIncomeField;
        }
        set {
            this.grossMonthlyIncomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GrossMonthlyIncomeSpecified {
        get {
            return this.grossMonthlyIncomeFieldSpecified;
        }
        set {
            this.grossMonthlyIncomeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Applicant_ID {
        get {
            return this.applicant_IDField;
        }
        set {
            this.applicant_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/Application.xsd")]
public partial class ApplicationOccupants {

    private int occupant_IDField;

    private string nameField;

    private System.DateTime dOBField;

    private bool dOBFieldSpecified;

    private int application_IDField;

    public string DriverLicenseNum {get; set;}

    public string SSN { get; set; }

    public int ApplicationID { get; set; }

    /// <remarks/>
    public int Occupant_ID {
        get {
            return this.occupant_IDField;
        }
        set {
            this.occupant_IDField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DOBSpecified {
        get {
            return this.dOBFieldSpecified;
        }
        set {
            this.dOBFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Application_ID {
        get {
            return this.application_IDField;
        }
        set {
            this.application_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Application.xsd")]
public partial class ApplicationPets {
    
    private int pet_IDField;
    
    private string typeField;
    
    private string breedField;
    
    private decimal depositField;
    
    private bool depositFieldSpecified;
    
    private int application_IDField;
    
    /// <remarks/>
    public int Pet_ID {
        get {
            return this.pet_IDField;
        }
        set {
            this.pet_IDField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Breed {
        get {
            return this.breedField;
        }
        set {
            this.breedField = value;
        }
    }
    
    /// <remarks/>
    public decimal Deposit {
        get {
            return this.depositField;
        }
        set {
            this.depositField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DepositSpecified {
        get {
            return this.depositFieldSpecified;
        }
        set {
            this.depositFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Application_ID {
        get {
            return this.application_IDField;
        }
        set {
            this.application_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Application.xsd")]
public partial class ApplicationResidentApplication {
    
    private int application_IDField;
    
    private int applicantsField;
    
    private int occupantsField;
    
    private int petsField;
    
    private int vehiclesField;
    
    private int propertyIDField;
    
    private bool propertyIDFieldSpecified;
    
    /// <remarks/>
    public int Application_ID {
        get {
            return this.application_IDField;
        }
        set {
            this.application_IDField = value;
        }
    }
    
    /// <remarks/>
    public int Applicants {
        get {
            return this.applicantsField;
        }
        set {
            this.applicantsField = value;
        }
    }
    
    /// <remarks/>
    public int Occupants {
        get {
            return this.occupantsField;
        }
        set {
            this.occupantsField = value;
        }
    }
    
    /// <remarks/>
    public int Pets {
        get {
            return this.petsField;
        }
        set {
            this.petsField = value;
        }
    }
    
    /// <remarks/>
    public int Vehicles {
        get {
            return this.vehiclesField;
        }
        set {
            this.vehiclesField = value;
        }
    }
    
    /// <remarks/>
    public int PropertyID {
        get {
            return this.propertyIDField;
        }
        set {
            this.propertyIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PropertyIDSpecified {
        get {
            return this.propertyIDFieldSpecified;
        }
        set {
            this.propertyIDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Application.xsd")]
public partial class ApplicationVehicles {
    
    private int vehicle_IDField;
    
    private string makeField;
    
    private string modelField;
    
    private int yearField;
    
    private bool yearFieldSpecified;
    
    private string colorField;
    
    private string licensePlateNumField;
    
    private string stateIssuedField;
    
    private int application_IDField;
    
    /// <remarks/>
    public int Vehicle_ID {
        get {
            return this.vehicle_IDField;
        }
        set {
            this.vehicle_IDField = value;
        }
    }
    
    /// <remarks/>
    public string Make {
        get {
            return this.makeField;
        }
        set {
            this.makeField = value;
        }
    }
    
    /// <remarks/>
    public string Model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    public int Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YearSpecified {
        get {
            return this.yearFieldSpecified;
        }
        set {
            this.yearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    public string LicensePlateNum {
        get {
            return this.licensePlateNumField;
        }
        set {
            this.licensePlateNumField = value;
        }
    }
    
    /// <remarks/>
    public string StateIssued {
        get {
            return this.stateIssuedField;
        }
        set {
            this.stateIssuedField = value;
        }
    }
    
    /// <remarks/>
    public int Application_ID {
        get {
            return this.application_IDField;
        }
        set {
            this.application_IDField = value;
        }
    }
}
