//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProps.codeLogic.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentHistory
    {
        public int EmpHistory_ID { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string StartEndDate { get; set; }
        public Nullable<int> GrossMonthlyIncome { get; set; }
        public int Applicant_ID { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
