//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProps.codeLogic.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupant
    {
        public int Occupant_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int Application_ID { get; set; }
        public string SSN { get; set; }
        public string Drivers_License_Num { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
