//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProps.codeLogic.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int Pet_ID { get; set; }
        public string Type { get; set; }
        public string Breed { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public int Application_ID { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
