//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProps.codeLogic.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalPropManageEntities : DbContext
    {
        public LocalPropManageEntities() : base("name=LocalPropManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressHistory> AddressHistories { get; set; }
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<EmploymentHistory> EmploymentHistories { get; set; }
        public virtual DbSet<MaintenceRequest> MaintenceRequests { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Resident> Residents { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<CustomField> CustomFields { get; set; }
        public virtual DbSet<Occupant> Occupants { get; set; }
        public virtual DbSet<UserPasswordReset> UserPasswordResets { get; set; }
    }
}
