//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProps.codeLogic.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public int ResidentID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<System.DateTime> MoveInDate { get; set; }
        public Nullable<System.DateTime> MoveOutDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Social { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
