//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProps.codeLogic.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Vehicle_ID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string Color { get; set; }
        public string LicensePlateNum { get; set; }
        public string StateIssued { get; set; }
        public int Application_ID { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
