//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProps.codeLogic.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public int WorkOrderID { get; set; }
        public int ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public int MaintenceRequestID { get; set; }
        public string CurrentStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> OrderStarted { get; set; }
        public Nullable<System.DateTime> OrderFinished { get; set; }
        public Nullable<System.DateTime> PromiseDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
